version: "3.9"
services:
  postgres:
    image: postgres:13.3
    container_name: db
    environment:
      POSTGRES_DB: ${db_name}
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_password}
    ports:
      - ${db_port}:5432

  backend:
    build: .
    external_links:
      - db:db
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - ./app:/app
    ports:
      - ${backend_port}:8000